export const SET_SINGER = 'SET_SINGER'

export const SET_RECOMLIST = 'SET_RECOMLIST'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULLSCREEN = 'SET_FULLSCREEN'

export const SET_PLAYLIST = 'SET_PALYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_MODE = 'SET_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_TOPLIST = 'SET_TOPLIST'

export const SET_CURRENT_URL = 'SET_CURRENT_URL'

export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'